//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Login { get; set; }
        public string EncryptedPassword { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime CreationDate { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
    }
}
