//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Diagnostics;

    public partial class Users
    {
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Key, Column(Order = 0)]
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Login { get; set; }
        public string EncryptedPassword { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public System.DateTime CreationDate { get; set; } = DateTime.Now;
        public string Country { get; set; }
        public string City { get; set; }

        //public void Show()
        //{
        //    Debug.WriteLine("UserID: " + UserID);
        //    Debug.WriteLine("FirstName: " + FirstName);
        //    Debug.WriteLine("LastName: " + LastName);
        //    Debug.WriteLine("BirthDate: " + BirthDate);
        //    Debug.WriteLine("Login: " + Login);
        //    Debug.WriteLine("EncryptedPassword: " + EncryptedPassword);
        //    Debug.WriteLine("Email: " + Email);
        //    Debug.WriteLine("Phone: " + Phone);
        //    Debug.WriteLine("CreationDate: " + CreationDate);
        //    Debug.WriteLine("Country: " + Country);
        //    Debug.WriteLine("City: " + City);
        //}
    }
}
