// <auto-generated />
namespace ShopApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class WorkinOnChat_UsingInverseProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WorkinOnChat_UsingInverseProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "202012152220545_WorkinOnChat_UsingInverseProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
