// <auto-generated />
namespace ShopApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ShopContextUpdate_AddedMessagesList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShopContextUpdate_AddedMessagesList));
        
        string IMigrationMetadata.Id
        {
            get { return "202012141457569_ShopContextUpdate_AddedMessagesList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
